# Generated by Django 4.0.4 on 2022-04-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('W', 'Women'), ('M', 'Men')], max_length=1)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
