# Generated by Django 4.0.4 on 2022-04-30 08:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('W', 'Women'), ('M', 'Men')], max_length=1)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100, null=True)),
                ('credit', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_item', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=50)),
                ('have_item', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=50)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': 'users_item',
            },
        ),
    ]
