# Generated by Django 4.0.4 on 2022-11-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_yourpooluser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourpooluser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='yourpooluser',
            name='last_name',
        ),
    ]
