# Generated by Django 4.0.4 on 2022-11-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_yourpooluser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='yourpooluser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='yourpooluser',
            name='username',
        ),
        migrations.AddField(
            model_name='yourpooluser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this user has completed the email verification process to allow login.', verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='yourpooluser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='yourpooluser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.  Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
