# Generated by Django 4.0.4 on 2022-11-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_yourpooluser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourpooluser',
            name='nickname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
