# Generated by Django 4.0.4 on 2022-11-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_yourpooluser_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourpooluser',
            name='is_email_verified',
        ),
        migrations.AddField(
            model_name='yourpooluser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='yourpooluser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
    ]
