# Generated by Django 4.0.4 on 2022-11-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_yourpooluser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourpooluser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='yourpooluser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='yourpooluser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
