# Generated by Django 4.0.4 on 2023-02-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_yourpooluser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourpooluser',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='yourpooluser',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=1000, null=True),
        ),
    ]
