version: "3.9"
   
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=moiza
      - POSTGRES_USER=moiza
      - POSTGRES_PASSWORD=moiza123
      - POSTGRES_HOST_AUTH_METHOD=trust
  
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=moiza
      - DB_USER=moiza
      - DB_PASSWORD=moiza123
      - DB_HOST=db
    depends_on:
      - db