# Generated by Django 4.0.4 on 2022-09-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PROFILE', '부적절한 프로필'), ('NAME', '부적절한 이름'), ('POLITICAL', '정치적 발언'), ('CURSE', '욕설'), ('SUGGESTIVE', '선정적인 발언'), ('FRAUD', '사기'), ('ETC', '기타')], max_length=10)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
