# Generated by Django 4.0.4 on 2022-05-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('HAT', 'HAT'), ('ACC', 'ACC'), ('TAB', 'TABLE'), ('CLO', 'CLOTHES'), ('SKIN', 'SKIN'), ('HAIR', 'HAIR')], max_length=4)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
