# Generated by Django 4.0.4 on 2022-05-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('room_category', models.CharField(choices=[('COFFEECHAT', '커피챗'), ('SPORT', '운동'), ('WALK', '산책'), ('ANIMAL', '반려동물'), ('HOBBY', '취미모임'), ('GAME', '게임'), ('STUDY', '스터디'), ('DRINK', '술자리'), ('FINANCIAL', '재테크'), ('CAREER', '커리어'), ('INFO', '동네정보'), ('FOOD', '밥친구')], max_length=15)),
                ('room_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('limit', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])),
                ('status', models.IntegerField(choices=[('0', 'off'), ('1', 'on')])),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('chat_member', models.JSONField()),
                ('user', models.ManyToManyField(to='users.user')),
            ],
            options={
                'db_table': 'chat_rooms',
            },
        ),
    ]
